version: '2.4'
services:
  db:
    image: mysql
    container_name: crudJavaMySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - crud:/var/lib/mysql

volumes:
  crud:
